

CREATE TABLE IF NOT EXISTS agri_field_stats (
    id                                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season                                  INTEGER NOT NULL,
    crop                                    VARCHAR NOT NULL,
    crop_group                              VARCHAR NOT NULL,

    level                                   VARCHAR NOT NULL,
    name                                    VARCHAR NOT NULL,
    parent                                  VARCHAR,

    field_count                             INTEGER,
    total_area                              NUMERIC,
    referenced_field_count                  INTEGER,
    referenced_area                         NUMERIC,
    test_field_count                        INTEGER,
    test_area                               NUMERIC,
    requires_on_site_observation_field_count INTEGER,
    requires_on_site_observation_area       NUMERIC,
    waiting_control_reference_field_count   INTEGER,
    waiting_control_reference_area          NUMERIC,
    rejected_reference_field_count          INTEGER,
    rejected_reference_area                 NUMERIC,
    suspicious_reference_field_count        INTEGER,
    suspicious_reference_area               NUMERIC,

    updated_at                              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT agri_field_stats_unique UNIQUE (season, crop, level, name, parent)
);

CREATE INDEX IF NOT EXISTS idx_agri_field_stats_season_level ON agri_field_stats (season, level);
CREATE INDEX IF NOT EXISTS idx_agri_field_stats_crop_group ON agri_field_stats (crop_group);
CREATE INDEX IF NOT EXISTS idx_agri_field_stats_name ON agri_field_stats (name);