CREATE TABLE IF NOT EXISTS agri_parcel_size_stats (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    il                  VARCHAR NOT NULL,
    crop                VARCHAR NOT NULL,
    parcels_under_4da   INTEGER,
    parcels_over_4da    INTEGER,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT agri_parcel_size_stats_unique UNIQUE (il, crop)
);

CREATE TABLE IF NOT EXISTS agri_planned_targets (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grup            VARCHAR,
    il              VARCHAR NOT NULL,
    crop            VARCHAR NOT NULL,
    period          VARCHAR NOT NULL,
    planned_count   NUMERIC,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT agri_planned_targets_unique UNIQUE (il, crop, period)
);

CREATE INDEX IF NOT EXISTS idx_agri_parcel_size_stats_il ON agri_parcel_size_stats (il);
CREATE INDEX IF NOT EXISTS idx_agri_planned_targets_il ON agri_planned_targets (il);