CREATE TABLE IF NOT EXISTS agri_reports (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    il             VARCHAR NOT NULL,
    kategori       VARCHAR NOT NULL,
    rapor_tarihi   DATE NOT NULL,
    notlar         VARCHAR,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Belirli bir il icin raporlari cekerken (findByIl) kullanilacak index
CREATE INDEX IF NOT EXISTS idx_agri_reports_il ON agri_reports (il);