

CREATE TABLE IF NOT EXISTS agri_field_classifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id       VARCHAR NOT NULL,          
    il              VARCHAR NOT NULL,          
    season          INTEGER,
    quarter         INTEGER,
    crops           VARCHAR,                   
    is_train        BOOLEAN NOT NULL DEFAULT FALSE,   
    is_test         BOOLEAN NOT NULL DEFAULT FALSE,   
    status          VARCHAR,
    source_created_at TIMESTAMP WITH TIME ZONE,
    fetched_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT agri_field_classifications_unique UNIQUE (source_id, il)
);

CREATE INDEX IF NOT EXISTS idx_agri_field_classifications_il ON agri_field_classifications (il);
CREATE INDEX IF NOT EXISTS idx_agri_field_classifications_season ON agri_field_classifications (season);