-- V5: apiuydu.tarimorman.gov.tr/fieldClassifications endpoint'inden
-- gelen "Tamamlanan İşlemler" (eğitim/tahmin) verisini saklar.
--
-- Bir kaynak kayıt (source_id) BİRDEN FAZLA ile ait olabiliyor (örn. bir
-- kayıt "Iğdır" ilinin 4 ilçesini birden kapsıyor olabilir, ya da teorik
-- olarak birden fazla İLİ de kapsayabilir) - bu yüzden il başına AYRI bir
-- satır tutuyoruz, (source_id, il) ikilisi benzersiz.

CREATE TABLE IF NOT EXISTS agri_field_classifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id       VARCHAR NOT NULL,          -- kaynaktaki 'id' (UUID)
    il              VARCHAR NOT NULL,          -- name'den çözümlenen il
    season          INTEGER,
    quarter         INTEGER,
    crops           VARCHAR,                   -- virgülle ayrılmış ürün listesi
    is_train        BOOLEAN NOT NULL DEFAULT FALSE,   -- "Eğitim"
    is_test         BOOLEAN NOT NULL DEFAULT FALSE,   -- "Tahmin"
    status          VARCHAR,
    source_created_at TIMESTAMP WITH TIME ZONE,
    fetched_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT agri_field_classifications_unique UNIQUE (source_id, il)
);

CREATE INDEX IF NOT EXISTS idx_agri_field_classifications_il ON agri_field_classifications (il);
CREATE INDEX IF NOT EXISTS idx_agri_field_classifications_season ON agri_field_classifications (season);